//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireSafety.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FireSafety.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все исполнители.
        /// </summary>
        internal static string AllPerformers {
            get {
                return ResourceManager.GetString("AllPerformers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Block {
            get {
                object obj = ResourceManager.GetObject("Block", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlueTank {
            get {
                object obj = ResourceManager.GetObject("BlueTank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlueTurret {
            get {
                object obj = ResourceManager.GetObject("BlueTurret", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BurnedHouse {
            get {
                object obj = ResourceManager.GetObject("BurnedHouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BurnedTree {
            get {
                object obj = ResourceManager.GetObject("BurnedTree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить выделение.
        /// </summary>
        internal static string CancelSelection {
            get {
                return ResourceManager.GetString("CancelSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарядить.
        /// </summary>
        internal static string ChargeCommandCharge {
            get {
                return ResourceManager.GetString("ChargeCommandCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бездействие.
        /// </summary>
        internal static string ChargeCommandNone {
            get {
                return ResourceManager.GetString("ChargeCommandNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Давление +1.
        /// </summary>
        internal static string ChargeCommandPressure1 {
            get {
                return ResourceManager.GetString("ChargeCommandPressure1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Давление +2.
        /// </summary>
        internal static string ChargeCommandPressure2 {
            get {
                return ResourceManager.GetString("ChargeCommandPressure2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнить запас.
        /// </summary>
        internal static string ChargeCommandRefuel {
            get {
                return ResourceManager.GetString("ChargeCommandRefuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Charged {
            get {
                object obj = ResourceManager.GetObject("Charged", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заряжающий.
        /// </summary>
        internal static string ChargePerformer {
            get {
                return ResourceManager.GetString("ChargePerformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ClearAlgorithm {
            get {
                object obj = ResourceManager.GetObject("ClearAlgorithm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить алгоритм танка.
        /// </summary>
        internal static string ClearTankAlgorithm {
            get {
                return ResourceManager.GetString("ClearTankAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить все алгоритмы.
        /// </summary>
        internal static string ClearWholeAlgorithm {
            get {
                return ResourceManager.GetString("ClearWholeAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить действие.
        /// </summary>
        internal static string DeleteAction {
            get {
                return ResourceManager.GetString("DeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteAction1 {
            get {
                object obj = ResourceManager.GetObject("DeleteAction1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документация.
        /// </summary>
        internal static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Down {
            get {
                object obj = ResourceManager.GetObject("Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fire {
            get {
                object obj = ResourceManager.GetObject("Fire", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon FireTank {
            get {
                object obj = ResourceManager.GetObject("FireTank", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreenTank {
            get {
                object obj = ResourceManager.GetObject("GreenTank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreenTurret {
            get {
                object obj = ResourceManager.GetObject("GreenTurret", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreyTank {
            get {
                object obj = ResourceManager.GetObject("GreyTank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreyTurret {
            get {
                object obj = ResourceManager.GetObject("GreyTurret", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дом.
        /// </summary>
        internal static string House {
            get {
                return ResourceManager.GetString("House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap House1 {
            get {
                object obj = ResourceManager.GetObject("House1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Озеро.
        /// </summary>
        internal static string Lake {
            get {
                return ResourceManager.GetString("Lake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lake1 {
            get {
                object obj = ResourceManager.GetObject("Lake1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to algorithm.
        /// </summary>
        internal static string MapParameterAlgorithm {
            get {
                return ResourceManager.GetString("MapParameterAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to capacity.
        /// </summary>
        internal static string MapParameterCurrentWaterCapacity {
            get {
                return ResourceManager.GetString("MapParameterCurrentWaterCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to house.
        /// </summary>
        internal static string MapParameterHouse {
            get {
                return ResourceManager.GetString("MapParameterHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxCapacity.
        /// </summary>
        internal static string MapParameterMaxWaterCapacity {
            get {
                return ResourceManager.GetString("MapParameterMaxWaterCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxPressure.
        /// </summary>
        internal static string MapParameterMaxWaterPressure {
            get {
                return ResourceManager.GetString("MapParameterMaxWaterPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to burns.
        /// </summary>
        internal static string MapParameterObjectBurns {
            get {
                return ResourceManager.GetString("MapParameterObjectBurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hitpoints.
        /// </summary>
        internal static string MapParameterObjectHitPoints {
            get {
                return ResourceManager.GetString("MapParameterObjectHitPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tank.
        /// </summary>
        internal static string MapParameterTank {
            get {
                return ResourceManager.GetString("MapParameterTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tree.
        /// </summary>
        internal static string MapParameterTree {
            get {
                return ResourceManager.GetString("MapParameterTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turret.
        /// </summary>
        internal static string MapParameterTurret {
            get {
                return ResourceManager.GetString("MapParameterTurret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wind.
        /// </summary>
        internal static string MapParameterWind {
            get {
                return ResourceManager.GetString("MapParameterWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to down.
        /// </summary>
        internal static string MapParameterWindDown {
            get {
                return ResourceManager.GetString("MapParameterWindDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downright.
        /// </summary>
        internal static string MapParameterWindDownRight {
            get {
                return ResourceManager.GetString("MapParameterWindDownRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        internal static string MapParameterWindLeft {
            get {
                return ResourceManager.GetString("MapParameterWindLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leftdown.
        /// </summary>
        internal static string MapParameterWindLeftDown {
            get {
                return ResourceManager.GetString("MapParameterWindLeftDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rigth.
        /// </summary>
        internal static string MapParameterWindRight {
            get {
                return ResourceManager.GetString("MapParameterWindRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rightup.
        /// </summary>
        internal static string MapParameterWindRightUp {
            get {
                return ResourceManager.GetString("MapParameterWindRightUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to up.
        /// </summary>
        internal static string MapParameterWindUp {
            get {
                return ResourceManager.GetString("MapParameterWindUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upleft.
        /// </summary>
        internal static string MapParameterWindUpLeft {
            get {
                return ResourceManager.GetString("MapParameterWindUpLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string MoveCommandBackward {
            get {
                return ResourceManager.GetString("MoveCommandBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад 45° пр. ч.с..
        /// </summary>
        internal static string MoveCommandBackwardRotate45CCW {
            get {
                return ResourceManager.GetString("MoveCommandBackwardRotate45CCW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад 45° по ч.с..
        /// </summary>
        internal static string MoveCommandBackwardRotate45CW {
            get {
                return ResourceManager.GetString("MoveCommandBackwardRotate45CW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вперед.
        /// </summary>
        internal static string MoveCommandForward {
            get {
                return ResourceManager.GetString("MoveCommandForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вперед 45° пр. ч.с..
        /// </summary>
        internal static string MoveCommandForwardRotate45CCW {
            get {
                return ResourceManager.GetString("MoveCommandForwardRotate45CCW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вперед 45° по ч.с..
        /// </summary>
        internal static string MoveCommandForwardRotate45CW {
            get {
                return ResourceManager.GetString("MoveCommandForwardRotate45CW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бездействие.
        /// </summary>
        internal static string MoveCommandNone {
            get {
                return ResourceManager.GetString("MoveCommandNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45° пр. ч.с..
        /// </summary>
        internal static string MoveCommandRotate45CCW {
            get {
                return ResourceManager.GetString("MoveCommandRotate45CCW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45° по ч.с..
        /// </summary>
        internal static string MoveCommandRotate45CW {
            get {
                return ResourceManager.GetString("MoveCommandRotate45CW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90° пр. ч.с..
        /// </summary>
        internal static string MoveCommandRotate90CCW {
            get {
                return ResourceManager.GetString("MoveCommandRotate90CCW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90° по ч.с..
        /// </summary>
        internal static string MoveCommandRotate90CW {
            get {
                return ResourceManager.GetString("MoveCommandRotate90CW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Водитель.
        /// </summary>
        internal static string MovePerformer {
            get {
                return ResourceManager.GetString("MovePerformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PinkTank {
            get {
                object obj = ResourceManager.GetObject("PinkTank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PinkTurret {
            get {
                object obj = ResourceManager.GetObject("PinkTurret", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pressure {
            get {
                object obj = ResourceManager.GetObject("Pressure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedTank {
            get {
                object obj = ResourceManager.GetObject("RedTank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedTurret {
            get {
                object obj = ResourceManager.GetObject("RedTurret", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перезагрузить.
        /// </summary>
        internal static string ReloadAlgorithm {
            get {
                return ResourceManager.GetString("ReloadAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скала.
        /// </summary>
        internal static string Rock {
            get {
                return ResourceManager.GetString("Rock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rock1 {
            get {
                object obj = ResourceManager.GetObject("Rock1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустить.
        /// </summary>
        internal static string RunAlgorithm {
            get {
                return ResourceManager.GetString("RunAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаг.
        /// </summary>
        internal static string StepAlgorithm {
            get {
                return ResourceManager.GetString("StepAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дерево.
        /// </summary>
        internal static string Tree {
            get {
                return ResourceManager.GetString("Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tree1 {
            get {
                object obj = ResourceManager.GetObject("Tree1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опустить.
        /// </summary>
        internal static string TurretCommandDown {
            get {
                return ResourceManager.GetString("TurretCommandDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бездействие.
        /// </summary>
        internal static string TurretCommandNone {
            get {
                return ResourceManager.GetString("TurretCommandNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45° пр. ч.с..
        /// </summary>
        internal static string TurretCommandRotate45CCW {
            get {
                return ResourceManager.GetString("TurretCommandRotate45CCW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45° по ч.с..
        /// </summary>
        internal static string TurretCommandRotate45CW {
            get {
                return ResourceManager.GetString("TurretCommandRotate45CW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90° пр. ч.с..
        /// </summary>
        internal static string TurretCommandRotate90CCW {
            get {
                return ResourceManager.GetString("TurretCommandRotate90CCW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90° по ч.с..
        /// </summary>
        internal static string TurretCommandRotate90CW {
            get {
                return ResourceManager.GetString("TurretCommandRotate90CW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выстрелить.
        /// </summary>
        internal static string TurretCommandShoot {
            get {
                return ResourceManager.GetString("TurretCommandShoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поднять.
        /// </summary>
        internal static string TurretCommandUp {
            get {
                return ResourceManager.GetString("TurretCommandUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наводчик.
        /// </summary>
        internal static string TurretPerformer {
            get {
                return ResourceManager.GetString("TurretPerformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Uncharged {
            get {
                object obj = ResourceManager.GetObject("Uncharged", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Up {
            get {
                object obj = ResourceManager.GetObject("Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Water {
            get {
                object obj = ResourceManager.GetObject("Water", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wind {
            get {
                object obj = ResourceManager.GetObject("Wind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вниз ↓.
        /// </summary>
        internal static string WindDown {
            get {
                return ResourceManager.GetString("WindDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вниз-вправо ↘.
        /// </summary>
        internal static string WindDownRight {
            get {
                return ResourceManager.GetString("WindDownRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Влево ←.
        /// </summary>
        internal static string WindLeft {
            get {
                return ResourceManager.GetString("WindLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Влево-вниз ↙.
        /// </summary>
        internal static string WindLeftDown {
            get {
                return ResourceManager.GetString("WindLeftDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вправо →.
        /// </summary>
        internal static string WindRight {
            get {
                return ResourceManager.GetString("WindRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вправо-вверх ↗.
        /// </summary>
        internal static string WindRightUp {
            get {
                return ResourceManager.GetString("WindRightUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вверх ↑.
        /// </summary>
        internal static string WindUp {
            get {
                return ResourceManager.GetString("WindUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вверх-влево ↖.
        /// </summary>
        internal static string WindUpLeft {
            get {
                return ResourceManager.GetString("WindUpLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YellowTank {
            get {
                object obj = ResourceManager.GetObject("YellowTank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YellowTurret {
            get {
                object obj = ResourceManager.GetObject("YellowTurret", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
